/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rock.paper.scissors;

/**
 *
 * @author zahirul
 */
public class userInterface extends javax.swing.JFrame {

    /**
     * Creates new form userInterface
     */
    public userInterface() {
        initComponents();
    }

    public String randomCMD() {
        int Max = 2;
        int Min = 0;
        int number = Min + (int) (Math.random() * ((Max - Min) + 1));
        if (number == 0) {
            computer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/paper.png")));
            return "paper";
        }
        if (number == 1) {
            computer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/rock.png")));
            return "rock";
        }
        computer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/scissors.png")));
        return "scissor";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        computer = new javax.swing.JLabel();
        userPaper = new javax.swing.JLabel();
        userRock = new javax.swing.JLabel();
        userScissors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Rock Paper Scissors");

        computer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/rock.png"))); // NOI18N

        userPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/paper.png"))); // NOI18N
        userPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPaperMouseClicked(evt);
            }
        });

        userRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/rock.png"))); // NOI18N
        userRock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRockMouseClicked(evt);
            }
        });

        userScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rock/paper/scissors/scissors.png"))); // NOI18N
        userScissors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userScissorsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(userPaper)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(userScissors)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(28, 28, 28)
                .addComponent(computer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPaper)
                    .addComponent(userRock)
                    .addComponent(userScissors))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPaperMouseClicked
        
        
        switch (randomCMD().charAt(0)) {
            case 'p':
                title.setText("Draw");
                break;
            case 's':
                title.setText("You lose");
                break;
            case 'r':
                title.setText("You Win");
                break;
        }

        
    }//GEN-LAST:event_userPaperMouseClicked

    private void userRockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRockMouseClicked
        
        switch (randomCMD().charAt(0)) {
            case 'r':
               title.setText("Draw");
                break;
            case 'p':
                title.setText("You lose");
                break;
            case 's':
                title.setText("You Win");
                break;
        }

    }//GEN-LAST:event_userRockMouseClicked

    private void userScissorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userScissorsMouseClicked
        
        switch (randomCMD().charAt(0)) {
            case 's':
                title.setText("Draw");
                break;
            case 'r':
               title.setText("You lose");
                break;
            case 'p':
                title.setText("You Win");
                break;
        }

    }//GEN-LAST:event_userScissorsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computer;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userPaper;
    private javax.swing.JLabel userRock;
    private javax.swing.JLabel userScissors;
    // End of variables declaration//GEN-END:variables
}
